### ISSUE TITLE
AttributeError: module 'wavelink' has no attribute 'abc'

### ISSUE THREAD

**Issue by RealmiRoblox** [shahriyardx/dismusic#7]
`Traceback (most recent call last):
  File "C:\Users\BaraK\Desktop\FadertyBot\main.py", line 2, in <module>
    import dismusic
  File "C:\Users\BaraK\Desktop\FadertyBot\venv\Lib\site-packages\dismusic\__init__.py", line 15, in <module>
    from .events import MusicEvents
  File "C:\Users\BaraK\Desktop\FadertyBot\venv\Lib\site-packages\dismusic\events.py", line 15, in <module>
    class MusicEvents(commands.Cog):
  File "C:\Users\BaraK\Desktop\FadertyBot\venv\Lib\site-packages\dismusic\events.py", line 20, in MusicEvents
    self, player: DisPlayer, track: wavelink.abc.Playable
                                    ^^^^^^^^^^^^
AttributeError: module 'wavelink' has no attribute 'abc'`

**Comment by mrmeloman** [comment]
The issue is still there )=
(no pressure, just updating)

Edit:
I got rid of this particular error by downgrading my wavelink to 1.2.4
However, there are some further errors, as this was written for a much older version of discord.py
I didn't get it to work, as I was not ready to downgrade discord.py

**Comment by shahriyardx** [comment]
> The issue is still there )= (no pressure, just updating)
> 
> Edit: I got rid of this particular error by downgrading my wavelink to 1.2.4 However, there are some further errors, as this was written for a much older version of discord.py I didn't get it to work, as I was not ready to downgrade discord.py

Yes it was released for dpy 1.6.2 or older I believe, it works with latest nextcord but not dpy 2.0 or higher

I will work on making it compatible with latest dpy, dpy prefix, dpy slash and nextcord latest too

I just need some time since there is no one to help me right now, and I am working on a lot of freelance projects

**Comment by mrmeloman** [comment]
> > The issue is still there )= (no pressure, just updating)
> > Edit: I got rid of this particular error by downgrading my wavelink to 1.2.4 However, there are some further errors, as this was written for a much older version of discord.py I didn't get it to work, as I was not ready to downgrade discord.py
> 
> Yes it was released for dpy 1.6.2 or older I believe, it works with latest nextcord but not dpy 2.0 or higher
> 
> I will work on making it compatible with latest dpy, dpy prefix, dpy slash and nextcord latest too
> 
> I just need some time since there is no one to help me right now, and I am working on a lot of freelance projects

Thank you a lot for your work!
